In [1]:
%matplotlib widget

In [2]:
import numpy as np
import emg3d 
import empymod as ep
import pandas as pd
from scipy.constants import mu_0
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm
import time
import sys
sys.path.insert(1, 'src')
import pickle 

from Plot import grid

## Upload data and sort

In [3]:
#OUT = np.load('data/data3D_slope10_40pos.pkl', allow_pickle=True)
OUT = np.load('data/data_s1_c1_uc.pkl', allow_pickle=True)

In [6]:
OUT

   geom  src_x  rec_x  midpx        op        ip
0    H2   -4.0   -2.0  -3.00  0.008163  0.000620
1    H4   -4.0    0.0  -2.00  0.021786  0.003973
2    H8   -4.0    4.0   0.00  0.039107  0.020318
3    V2   -4.0   -2.0  -3.00  0.009936  0.000379
4    V4   -4.0    0.0  -2.00  0.034350  0.002526
..  ...    ...    ...    ...       ...       ...
4    V4   39.0   43.0  41.00  0.036168  0.002867
5    V8   39.0   47.0  43.00  0.106489  0.016644
6    P2   39.0   41.1  40.05  0.008568  0.000178
7    P4   39.0   43.1  41.05  0.050527  0.002559
8    P8   39.0   47.1  43.05  0.132592  0.016178

[396 rows x 6 columns]

In [4]:
OUT_sorted = OUT.sort_values(by='geom')

In [5]:
OUT_sorted

   geom  src_x  rec_x  midpx        op        ip
0    H2   -4.0   -2.0   -3.0  0.008163  0.000620
0    H2   27.0   29.0   28.0  0.008524  0.000686
0    H2   14.0   16.0   15.0  0.008358  0.000656
0    H2   28.0   30.0   29.0  0.008539  0.000688
0    H2   37.0   39.0   38.0  0.008638  0.000706
..  ...    ...    ...    ...       ...       ...
5    V8   15.0   23.0   19.0  0.102341  0.015445
5    V8   26.0   34.0   30.0  0.104553  0.016057
5    V8   36.0   44.0   40.0  0.106148  0.016525
5    V8   16.0   24.0   20.0  0.102573  0.015504
5    V8    8.0   16.0   12.0  0.101132  0.015076

[396 rows x 6 columns]

In [14]:
npos = int(len(OUT_sorted)/9)

In [15]:
npos

2

In [16]:
data_3D = np.zeros((npos-3,18))

pos=0
for p in range(-3,npos):
    print(OUT_sorted.loc[(OUT_sorted.midpx > p+.06) & (OUT_sorted.midpx <p +1.06)])

    dat = np.hstack((OUT_sorted.loc[(OUT_sorted.midpx > p+.06) & (OUT_sorted.midpx <=p +1.06)]['op'],
                     OUT_sorted.loc[(OUT_sorted.midpx > p+.06) & (OUT_sorted.midpx <=p +1.06)]['ip'])) 
    if dat.size == 0:
        continue
    if dat.size == 18:
        data_3D[pos,:] = dat
        #print('pos:', pos)
        pos += 1

ValueError: negative dimensions are not allowed

In [77]:
np.save('data/data_3D_slope10_40pos_sorted', data_3D[1:41])

In [78]:
np.shape(data_3D[1:41])

(40, 18)